// ───────────────────────────────────────────────────────────────────────────
// Schema: Screen 9 — Final Course Blueprint
// ───────────────────────────────────────────────────────────────────────────
// Per Appendix A:
// - Orchestrator assembles from all 8 prior approved outputs
// - NOT generated by Creator
// - Validates asset coverage, required outputs present, module counts match

import { z } from 'zod'
import { experiencePlanSchema } from './screen_8'
import { moduleMapEntrySchema } from './screen_5'
import { moduleAssetsSchema } from './screen_7'
import { chapterAuditEntrySchema } from './screen_4'
import { lessonMapCreatorSchema } from './screen_6'

export const blueprintSchema = z.object({
  blueprint_id: z.string().uuid().optional(),  // assigned by DB
  user_id: z.string().uuid(),
  blueprint_version: z.number().int().min(1),
  module_8_completion_status: z.enum(['draft', 'in_progress', 'blueprint_approved']),

  // Core metadata
  course_name_draft: z.string().min(5),
  course_transformation_statement: z.string().min(40),
  course_depth: z.string(),
  delivery_format: z.string(),
  duration: z.string().optional(),
  target_learner: z.string(),
  course_outcome: z.string(),
  unique_method: z.string(),

  // Counts
  total_modules: z.number().int().min(1).max(7),
  total_lessons: z.number().int().min(1),
  total_implementation_assets: z.number().int().min(1),

  // Linked prior outputs
  chapter_audit: z.array(chapterAuditEntrySchema),
  module_map: z.array(moduleMapEntrySchema),
  lesson_map: z.array(lessonMapCreatorSchema),
  asset_map: z.array(moduleAssetsSchema),
  experience_plan: experiencePlanSchema,

  // QC rollup
  validator_scores_summary: z.record(z.string(), z.number()).optional(),

  // Assembly metadata
  created_at: z.string().optional(),
  blueprint_approved_at: z.string().nullable().optional(),
})

export type BlueprintPayload = z.infer<typeof blueprintSchema>
