-- Add market_language column to clarity_sentences.
-- Stores a categorized language pack for the user's specific niche market —
-- everyday phrases, emotional words, world references, jargon. Auto-captured
-- when the clarity sentence is finalized; injected into every downstream
-- module's AI prompt so all generated content speaks the same niche bubble.
--
-- Run in Supabase SQL Editor.

ALTER TABLE clarity_sentences
ADD COLUMN IF NOT EXISTS market_language jsonb;

COMMENT ON COLUMN clarity_sentences.market_language IS
  'Categorized niche language pack: { everyday_phrases, emotional_words, world_references, jargon }. ~30 entries total. Generated by lib/marketLanguage.ts after clarity is saved; lazy-backfills if missing.';
