// ─── Preferred Vocabulary ─────────────────────────────────────────────────
// Top 300 English words used naturally by Filipinos on Reddit
// (r/Philippines, r/AskPH, r/CasualPH, r/buhaydigital, r/studentsph,
// r/adultingph, r/peyups). Sourced from ~8,900 conversational comments
// after stopword + Tagalog homonym + bot-comment filtering.
//
// Usage: feed this list into AI prompts as a soft preference — "Lean on
// natural conversational English. Your audience uses words like these."
// Gentler than the hard-banned list in bannedWords.ts.

export const PREFERRED_VOCABULARY = [
  "people", // 435
  "time", // 386
  "even", // 346
  "work", // 304
  "good", // 277
  "it's", // 273
  "years", // 262
  "after", // 226
  "life", // 197
  "before", // 190
  "don't", // 188
  "since", // 184
  "never", // 182
  "family", // 173
  "i'm", // 169
  "first", // 163
  "better", // 159
  "year", // 152
  "back", // 151
  "right", // 149
  "man", // 139
  "sure", // 138
  "last", // 137
  "day", // 137
  "way", // 136
  "congrats", // 134
  "student", // 127
  "actually", // 127
  "always", // 126
  "take", // 126
  "point", // 125
  "hope", // 124
  "job", // 120
  "experience", // 119
  "car", // 117
  "that's", // 116
  "client", // 115
  "school", // 114
  "long", // 113
  "use", // 113
  "every", // 112
  "someone", // 112
  "part", // 110
  "while", // 109
  "thing", // 106
  "lot", // 106
  "feel", // 106
  "something", // 105
  "students", // 104
  "during", // 104
  "try", // 103
  "best", // 102
  "true", // 100
  "money", // 97
  "around", // 96
  "doing", // 95
  "bad", // 94
  "new", // 94
  "free", // 93
  "already", // 93
  "agree", // 92
  "college", // 91
  "parents", // 91
  "things", // 90
  "through", // 89
  "months", // 89
  "high", // 88
  "real", // 87
  "help", // 83
  "old", // 83
  "next", // 83
  "let", // 82
  "once", // 81
  "least", // 81
  "month", // 81
  "mean", // 80
  "enough", // 80
  "you're", // 80
  "remember", // 80
  "look", // 79
  "city", // 79
  "love", // 79
  "country", // 78
  "keep", // 78
  "maybe", // 78
  "social", // 78
  "find", // 77
  "though", // 77
  "super", // 76
  "week", // 76
  "especially", // 75
  "left", // 75
  "everything", // 75
  "side", // 74
  "check", // 74
  "per", // 74
  "friends", // 74
  "gets", // 73
  "days", // 73
  "case", // 70
  "news", // 70
  "working", // 70
  "health", // 70
  "food", // 70
  "happy", // 70
  "another", // 69
  "without", // 69
  "having", // 69
  "they're", // 69
  "ask", // 69
  "less", // 69
  "reason", // 69
  "usually", // 69
  "issue", // 68
  "world", // 68
  "course", // 68
  "myself", // 68
  "doesn't", // 67
  "against", // 67
  "off", // 67
  "used", // 67
  "started", // 66
  "end", // 65
  "give", // 65
  "different", // 65
  "place", // 65
  "big", // 65
  "ago", // 65
  "support", // 64
  "far", // 64
  "start", // 64
  "until", // 64
  "pay", // 63
  "everyone", // 62
  "question", // 62
  "mind", // 62
  "anything", // 62
  "call", // 61
  "name", // 61
  "video", // 61
  "live", // 61
  "media", // 61
  "feeling", // 61
  "kind", // 61
  "friend", // 60
  "clients", // 60
  "hospital", // 60
  "instead", // 59
  "wrong", // 59
  "makes", // 59
  "learn", // 59
  "believe", // 58
  "getting", // 58
  "safe", // 58
  "system", // 58
  "price", // 58
  "understand", // 57
  "class", // 57
  "ever", // 57
  "problem", // 56
  "rate", // 56
  "probably", // 56
  "company", // 56
  "future", // 56
  "hard", // 55
  "driver", // 55
  "online", // 55
  "kids", // 54
  "group", // 54
  "away", // 54
  "means", // 54
  "either", // 54
  "nothing", // 54
  "almost", // 54
  "proud", // 54
  "med", // 54
  "plan", // 53
  "mom", // 53
  "normal", // 53
  "change", // 53
  "level", // 52
  "imagine", // 52
  "buy", // 52
  "monthly", // 52
  "whole", // 51
  "business", // 51
  "term", // 50
  "great", // 50
  "afford", // 50
  "plus", // 50
  "doctor", // 50
  "personal", // 49
  "girl", // 49
  "can't", // 49
  "due", // 49
  "tell", // 49
  "white", // 49
  "soon", // 49
  "home", // 49
  "research", // 48
  "fake", // 48
  "ones", // 48
  "local", // 48
  "worth", // 48
  "done", // 48
  "office", // 48
  "rather", // 48
  "using", // 48
  "area", // 47
  "compared", // 47
  "stop", // 47
  "chance", // 47
  "yet", // 47
  "common", // 47
  "yrs", // 47
  "skills", // 47
  "run", // 46
  "salary", // 46
  "yourself", // 46
  "i've", // 45
  "cause", // 45
  "person", // 45
  "put", // 45
  "financial", // 45
  "rest", // 45
  "black", // 45
  "focus", // 45
  "oil", // 45
  "management", // 45
  "congratulations", // 45
  "apply", // 45
  "current", // 44
  "nice", // 44
  "happened", // 44
  "honestly", // 44
  "based", // 44
  "read", // 44
  "sense", // 44
  "deserve", // 44
  "early", // 44
  "struggle", // 43
  "full", // 43
  "sad", // 43
  "history", // 43
  "set", // 43
  "curious", // 43
  "bought", // 43
  "paid", // 43
  "data", // 42
  "actual", // 41
  "between", // 41
  "top", // 41
  "literally", // 41
  "strong", // 41
  "simple", // 41
  "halos", // 41
  "times", // 41
  "type", // 41
  "performance", // 41
  "looking", // 41
  "come", // 41
  "community", // 40
  "else", // 40
  "report", // 40
  "open", // 40
  "stay", // 40
  "situation", // 40
  "care", // 40
  "amoy", // 40
  "doc", // 40
  "matter", // 39
  "dead", // 39
  "themselves", // 39
  "answer", // 39
  "leader", // 39
  "died", // 39
  "living", // 39
  "bank", // 39
  "cost", // 39
  "issues", // 39
  "non", // 39
  "wow", // 39
  "socks", // 39
  "niche", // 39
  "negros", // 38
  "hand", // 38
  "there's", // 38
  "fact", // 38
  "legal", // 38
  "human", // 38
  "looks", // 38
  "unless", // 38
  "saying", // 38
  "mama", // 38
  "needs", // 38
  "late", // 38
  "digits", // 38
  "fan", // 38
  "example", // 37
  "thinking", // 37
]

// Builds a one-liner prompt fragment listing the top-N preferred words.
// Pass into system prompts as a soft style guide — NOT a hard rule.
// Audience-agnostic: this defines the WRITING REGISTER, not the audience.
// The audience itself comes from the user's clarity sentence (target_market)
// which is injected into prompts separately.
export function buildVocabularyHint(topN = 80): string {
  const words = PREFERRED_VOCABULARY.slice(0, topN).join(", ")
  return `WRITING REGISTER: Write in casual, conversational English the way
Filipinos actually talk day-to-day, with light natural Taglish warmth where
it fits. Lean on plain everyday words they really use, like: ${words}. Avoid
hype-style, marketing-speak, or academic English. Write the way a Filipino
friend would explain something over coffee — not the way ChatGPT writes.`
}
