// ───────────────────────────────────────────────────────────────────────────
// Module 8 — Blueprint Assembly (Screen 9)
// ───────────────────────────────────────────────────────────────────────────
//
// Per Doc 3 + Doc 5:
// - Orchestrator assembles from all approved outputs (Screens 1-8)
// - NOT generated by Creator Agent
// - Validates required outputs present + asset coverage rule
// - Updates blueprint_version each time (starts at 1, increments on re-approval)

import { getAllApprovedOutputs } from './persistence'
import { blueprintSchema, type BlueprintPayload } from './schemas/blueprint'

export interface BlueprintAssemblyResult {
  blueprint: BlueprintPayload
  validation_warnings: string[]
  ready_for_approval: boolean
  missing_screens: number[]
}

/**
 * Collects all approved outputs and assembles the final blueprint.
 * Returns ready_for_approval = true only if all required screens are approved
 * and all validation rules pass.
 */
export async function assembleBlueprint(args: {
  userId: string
  sessionId: string
  currentVersion: number
}): Promise<BlueprintAssemblyResult> {
  const approved = await getAllApprovedOutputs(args.sessionId)

  const warnings: string[] = []
  const missingScreens: number[] = []

  // Required screens: 1 through 8 must all be approved
  for (let i = 1; i <= 8; i++) {
    if (!approved[i]) missingScreens.push(i)
  }

  if (missingScreens.length > 0) {
    warnings.push(`Missing approved output from screen(s): ${missingScreens.join(', ')}`)
  }

  const screen2 = approved[2] as Record<string, unknown> | undefined
  const screen3 = approved[3] as Record<string, unknown> | undefined
  const screen4 = approved[4] as Record<string, unknown> | undefined
  const screen5 = approved[5] as Record<string, unknown> | undefined
  const screen6 = approved[6] as Record<string, unknown> | undefined
  const screen7 = approved[7] as Record<string, unknown> | undefined
  const screen8 = approved[8] as Record<string, unknown> | undefined

  // ── Asset coverage check (Doc 5: RULE_010 for blueprint stage) ──────
  if (screen5 && screen7) {
    const moduleMap = (screen5.module_map as Array<{ module_number: number }> | undefined) ?? []
    const assetMap = (screen7.asset_map as Array<{ module_number: number; assets?: unknown[] }> | undefined) ?? []
    for (const mod of moduleMap) {
      const assets = assetMap.find(a => a.module_number === mod.module_number)
      const count = assets?.assets?.length ?? 0
      if (count < 1) {
        warnings.push(`Module ${mod.module_number} has 0 assets; minimum is 1 for approval.`)
      }
      if (count > 3) {
        warnings.push(`Module ${mod.module_number} has ${count} assets; maximum is 3.`)
      }
    }
  }

  // ── Lesson coverage check: every module should have lessons ──────────
  if (screen5 && screen6) {
    const moduleMap = (screen5.module_map as Array<{ module_number: number }> | undefined) ?? []
    const lessonMap = (screen6.lesson_map as Array<{ module_number: number; lessons?: unknown[] }> | undefined) ?? []
    for (const mod of moduleMap) {
      const lessons = lessonMap.find(l => l.module_number === mod.module_number)
      if (!lessons || (lessons.lessons?.length ?? 0) === 0) {
        warnings.push(`Module ${mod.module_number} has no lessons.`)
      }
    }
  }

  // ── Assemble the blueprint payload ────────────────────────────────────
  const totalModules = ((screen5?.module_map as unknown[] | undefined)?.length) ?? 0
  const totalLessons = ((screen6?.lesson_map as Array<{ lessons?: unknown[] }> | undefined) ?? [])
    .reduce((sum, m) => sum + (m.lessons?.length ?? 0), 0)
  const totalAssets = ((screen7?.asset_map as Array<{ assets?: unknown[] }> | undefined) ?? [])
    .reduce((sum, m) => sum + (m.assets?.length ?? 0), 0)

  const blueprint: BlueprintPayload = {
    user_id: args.userId,
    blueprint_version: args.currentVersion,
    module_8_completion_status: warnings.length === 0 && missingScreens.length === 0 ? 'blueprint_approved' : 'draft',

    course_name_draft:                (screen5?.course_title as string) ?? '',
    course_transformation_statement:  (screen2?.course_transformation_statement as string) ?? '',
    course_depth:                     (screen3?.course_depth as string) ?? '',
    delivery_format:                  (screen3?.delivery_format as string) ?? '',
    duration:                         (screen2?.duration_commitment as string) ?? undefined,
    target_learner:                   (screen2?.target_learner as string) ?? '',
    course_outcome:                   (screen2?.course_outcome as string) ?? '',
    unique_method:                    (screen2?.unique_method as string) ?? '',

    total_modules: totalModules,
    total_lessons: totalLessons,
    total_implementation_assets: totalAssets,

    chapter_audit:   (screen4?.chapter_audit as BlueprintPayload['chapter_audit']) ?? [],
    module_map:      (screen5?.module_map as BlueprintPayload['module_map']) ?? [],
    lesson_map:      (screen6?.lesson_map as BlueprintPayload['lesson_map']) ?? [],
    asset_map:       (screen7?.asset_map as BlueprintPayload['asset_map']) ?? [],
    experience_plan: (screen8?.plan as BlueprintPayload['experience_plan']) ?? {
      delivery_cadence:       'self_paced_unlocked',
      support_channel:        'none',
      community_access:       'none',
      live_session_frequency: 'none',
      completion_model:       'self_report',
      certification:          'none',
    },
  }

  // Schema-validate the assembly
  const result = blueprintSchema.safeParse(blueprint)
  if (!result.success) {
    warnings.push(`Blueprint schema validation failed: ${JSON.stringify(result.error.issues).substring(0, 400)}`)
    return {
      blueprint,
      validation_warnings: warnings,
      ready_for_approval: false,
      missing_screens: missingScreens,
    }
  }

  return {
    blueprint: result.data,
    validation_warnings: warnings,
    ready_for_approval: warnings.length === 0 && missingScreens.length === 0,
    missing_screens: missingScreens,
  }
}
